"""add job table

Revision ID: 57f2d5e59287
Revises: 7a223fd0a20c
Create Date: 2026-08-29 13:23:07.923497

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57f2d5e59287"
down_revision: str | Sequence[str] | None = "7a223fd0a20c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("pending", "running", "succeeded", "failed", name="job_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("detail", sa.String(length=200), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_job_kind_created_at",
        "job",
        ["kind", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_job_active_kind",
        "job",
        ["kind"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_job_active_kind",
        table_name="job",
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.drop_index("ix_job_kind_created_at", table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###
    # Hand-written: create_table creates the enum type implicitly, drop_table
    # does not remove it, so a downgrade would leave it orphaned and the next
    # upgrade would fail with "type job_status already exists".
    postgresql.ENUM(name="job_status").drop(op.get_bind(), checkfirst=True)
