"""initial schema

Revision ID: 7a223fd0a20c
Revises:
Create Date: 2026-08-29 12:41:19.481781

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a223fd0a20c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "move",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("damage_class", sa.String(length=20), nullable=False),
        sa.Column("power", sa.Integer(), nullable=True),
        sa.Column("accuracy", sa.Integer(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("effect_chance", sa.Integer(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_move_type", "move", ["type"], unique=False)
    op.create_table(
        "pokemon",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sprite_url", sa.String(length=500), nullable=True),
        sa.Column("type1", sa.String(length=20), nullable=False),
        sa.Column("type2", sa.String(length=20), nullable=True),
        sa.Column("base_hp", sa.Integer(), nullable=False),
        sa.Column("base_atk", sa.Integer(), nullable=False),
        sa.Column("base_def", sa.Integer(), nullable=False),
        sa.Column("base_spatk", sa.Integer(), nullable=False),
        sa.Column("base_spdef", sa.Integer(), nullable=False),
        sa.Column("base_speed", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stats_hash", sa.String(length=64), nullable=False),
        sa.Column("types_hash", sa.String(length=64), nullable=False),
        sa.Column("moves_hash", sa.String(length=64), nullable=False),
        sa.Column("sprite_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pokemon_name_prefix",
        "pokemon",
        ["name"],
        unique=False,
        postgresql_ops={"name": "text_pattern_ops"},
    )
    op.create_index("ix_pokemon_type1", "pokemon", ["type1"], unique=False)
    op.create_index("ix_pokemon_type2", "pokemon", ["type2"], unique=False)
    op.create_table(
        "sync_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_scanned", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("changes_found", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "source",
            postgresql.ENUM("live", "fixture", "stale", name="sync_source"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_sync_run_started_at", "sync_run", ["started_at"], unique=False)
    op.create_table(
        "type_chart",
        sa.Column("attacking_type", sa.String(length=20), nullable=False),
        sa.Column("defending_type", sa.String(length=20), nullable=False),
        sa.Column("multiplier", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("attacking_type", "defending_type"),
    )
    op.create_table(
        "data_change",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sync_run_id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("field_path", sa.String(length=200), nullable=False),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["sync_run_id"], ["sync_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_data_change_detected_at",
        "data_change",
        [sa.literal_column("detected_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_data_change_entity", "data_change", ["entity_type", "entity_id"], unique=False
    )
    op.create_index("ix_data_change_sync_run_id", "data_change", ["sync_run_id"], unique=False)
    op.create_table(
        "pokemon_ability",
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("ability_name", sa.String(length=100), nullable=False),
        sa.Column("is_hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(["pokemon_id"], ["pokemon.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pokemon_id", "ability_name"),
    )
    op.create_table(
        "pokemon_move",
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("move_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["move_id"], ["move.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pokemon_id"], ["pokemon.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("pokemon_id", "move_id"),
    )
    op.create_index("ix_pokemon_move_move_id", "pokemon_move", ["move_id"], unique=False)
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_team_user_id", "team", ["user_id"], unique=False)
    op.create_table(
        "change_ack",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("data_change_id", sa.Integer(), nullable=False),
        sa.Column(
            "acknowledged_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["data_change_id"], ["data_change.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "data_change_id"),
    )
    op.create_index("ix_change_ack_data_change_id", "change_ack", ["data_change_id"], unique=False)
    op.create_table(
        "team_member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("pokemon_id", sa.Integer(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.CheckConstraint("slot BETWEEN 1 AND 6", name="ck_team_member_slot_range"),
        sa.ForeignKeyConstraint(["pokemon_id"], ["pokemon.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "pokemon_id", name="uq_team_member_team_pokemon"),
        sa.UniqueConstraint("team_id", "slot", name="uq_team_member_team_slot"),
    )
    op.create_index("ix_team_member_pokemon_id", "team_member", ["pokemon_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_team_member_pokemon_id", table_name="team_member")
    op.drop_table("team_member")
    op.drop_index("ix_change_ack_data_change_id", table_name="change_ack")
    op.drop_table("change_ack")
    op.drop_index("ix_team_user_id", table_name="team")
    op.drop_table("team")
    op.drop_index("ix_pokemon_move_move_id", table_name="pokemon_move")
    op.drop_table("pokemon_move")
    op.drop_table("pokemon_ability")
    op.drop_index("ix_data_change_sync_run_id", table_name="data_change")
    op.drop_index("ix_data_change_entity", table_name="data_change")
    op.drop_index("ix_data_change_detected_at", table_name="data_change")
    op.drop_table("data_change")
    op.drop_table("type_chart")
    op.drop_index("ix_sync_run_started_at", table_name="sync_run")
    op.drop_table("sync_run")
    op.drop_index("ix_pokemon_type2", table_name="pokemon")
    op.drop_index("ix_pokemon_type1", table_name="pokemon")
    op.drop_index(
        "ix_pokemon_name_prefix", table_name="pokemon", postgresql_ops={"name": "text_pattern_ops"}
    )
    op.drop_table("pokemon")
    op.drop_index("ix_move_type", table_name="move")
    op.drop_table("move")
    op.drop_table("app_user")
    # ### end Alembic commands ###
    # Hand-written. The sync_source enum type is created implicitly as a side
    # effect of create_table, but drop_table does not remove it, so a downgrade
    # leaves the type orphaned and the next upgrade fails with
    # "type sync_source already exists".
    postgresql.ENUM(name="sync_source").drop(op.get_bind(), checkfirst=True)
